[package]
default-run = "poem-admin"
edition = "2021"
name = "poem-admin"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

app = {path = "../app"}
configs = {path = "../configs"}
db = {path = "../db"}

# axum
axum = {version = "0.5", features = ["headers"]}
tokio = {version = "1", features = ["rt-multi-thread", "macros", "parking_lot", "signal"]}
tower-http = {version = "0.3", features = ["cors"]}

#
tracing = "0.1"
tracing-appender = "0.2"
# tracing-log = "0.1"
tracing-subscriber = {version = "0.3", features = ["json", "env-filter", "local-time", "registry"]}
