[package]
default-run = "axum-admin"
edition = "2021"
name = "axum-admin"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

app = {path = "../app"}
configs = {path = "../configs"}
db = {path = "../db"}

# axum
axum = {version = "0.5", features = ["headers","http2"]}
axum-server = { version = "0.4", features = ["tls-rustls"] }
axum-extra = { version = "0.3",features = ["spa"]}
hyper = { version = "0.14", features = ["full"] }
tokio = {version = "1", features = ["rt-multi-thread", "macros", "parking_lot", "signal"]}
tower-http = {version = "0.3", features = ["cors","fs","compression-gzip"]}  #compression-gzip

#
tracing = "0.1"
tracing-appender = "0.2"
# tracing-log = "0.1"
tracing-subscriber = {version = "0.3", features = ["json", "env-filter", "local-time", "registry"]}
