[package]
edition = "2021"
name = "poem-admin"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

poem = "1"
# poem-openapi = "1"
headers = "0.3.5"
jsonwebtoken = "7.2.0"
once_cell = "1.8"
serde = {version = "1.0", features = ["derive"]}
serde_json = "1.0"
tokio = {version = "1.13.0", features = ["rt-multi-thread", "macros"]}
toml = "0.5.8"
tracing = {git = "https://github.com/tokio-rs/tracing.git"}
tracing-appender = {git = "https://github.com/tokio-rs/tracing.git"}
tracing-subscriber = {git = "https://github.com/tokio-rs/tracing.git", version = "0.3", features = ["json", "env-filter"]}
