[package]
edition = "2021"
name = "poem-admin"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[profile.release]
codegen-units = 1 
debug = false 
lto = true 
opt-level = "z" # Optimize for size.
panic = 'abort' 

[dependencies]
# anyhow = "1.0.51"
# env_logger = "0.9"
chrono = {version = "0.4", features = ["serde"]}
headers = "0.3.5"
jsonwebtoken = "7.2.0"
once_cell = "1.9.0"
poem = {version = "1.2.5", features = ["static-files"]}
# poem = "=1.1.1"
# poem-derive = "=1.1.1"
# poem-openapi = "1.1.1"
# 用于生成可排序的唯一id
# lazy_static = "1.4.0"
scru128 = "1.0.0"
serde = {version = "1.0", features = ["derive"]}
serde_json = "1"
# tokio = {version = "1", features = ["rt-multi-thread", "macros", "parking_lot", "signal"]}
tokio = {version = "1", features = ["full"]}
toml = "0.5.8"
# tracing
tracing = {git = "https://github.com/tokio-rs/tracing.git"}
tracing-appender = {git = "https://github.com/tokio-rs/tracing.git"}
tracing-log = {git = "https://github.com/tokio-rs/tracing.git"}
tracing-subscriber = {git = "https://github.com/tokio-rs/tracing.git", version = "0.3", features = ["json", "env-filter", "local-time"]}
# tracing = "0.1.29"
# tracing-appender = "0.2.0"
# tracing-log = "0.1.2"
# tracing-subscriber = {version = "0.3.5", features = ["json", "env-filter", "local-time"]}

sea_orm_casbin_adapter = "0.2.4"
# sea_orm_casbin_adapter = {git = "https://github.com/lingdu1234/sea_orm_casbin_adapter.git"}

#  随机数
md5 = "0.7.0"
rand = "0.8.4"
#  验证器
regex = "1.5.4"
validator = {version = "0.14.0", features = ["derive", "phone"]}
# 验证码
captcha_rust = "0.1.3"
# sea-orm
[dependencies.sea-orm]
default-features = false
features = ["macros", "runtime-tokio-native-tls"]
version = "0.5.0"

[features]
default = ["postgres", "mysql"]
mysql = ["sea-orm/sqlx-mysql"]
postgres = ["sea-orm/sqlx-postgres"]
sqlite = ["sea-orm/sqlx-sqlite"]
