[package]
edition = "2021"
name = "poem-admin"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

chrono = {version = "0.4", features = ["serde"]}
env_logger = "0.9"
headers = "0.3.5"
jsonwebtoken = "7.2.0"
once_cell = "1.8"
poem = "1"
poem-openapi = "1"
# 用于生成可排序的唯一id
scru128 = "0.2.0"
serde = {version = "1.0", features = ["derive"]}
serde_json = "1.0"
tokio = {version = "1.13.0", features = ["rt-multi-thread", "macros"]}
toml = "0.5.8"

# tracing
tracing = {git = "https://github.com/tokio-rs/tracing.git"}
tracing-appender = {git = "https://github.com/tokio-rs/tracing.git"}
tracing-log = {git = "https://github.com/tokio-rs/tracing.git"}
tracing-subscriber = {git = "https://github.com/tokio-rs/tracing.git", version = "0.3", features = ["json", "env-filter"]}

# sea-orm
[dependencies.sea-orm]
# path = "../../" # remove this line in your own project
default-features = false
features = ["macros", "runtime-tokio-native-tls"]
version = "^0.3.0"

[features]
default = ["sqlx-mysql"]
sqlx-mysql = ["sea-orm/sqlx-mysql"]
sqlx-postgres = ["sea-orm/sqlx-postgres"]
